kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-certs
  namespace: test-kafka-ui-kowl
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storageclass
  volumeMode: Filesystem
  capacity:
    storage: 1Gi